spring.application.name=mcp-app
server.port=8081

#open ai configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}

#logging configuration
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#mcp server configuration
spring.ai.mcp.client.stdio.servers-configuration=classpath:servers.json